//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpotifyClone.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Song
    {
        public int M_Id { get; set; }
        public string M_Name { get; set; }
        public string M_File { get; set; }
        public HttpPostedFileBase M_Fil { get; set; }
        public string M_Desc { get; set; }
        public int Cat_fid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
